version: '2'

services:
 # microservice city data monitor
    cityreporter:
        image: cityreporter
        network_mode: host
        ports:
            - "8089:8080"
        #volumes:
        #- /weka_ksam/:/tmp/weka
