version: '2'

services:
 # microservice city data monitor
    cityreporter:
        image: edithzavala/cityreporter
        network_mode: host
        ports:
            - "8089:8080"
        command: "application.json --server.port=8089"
        volumes:
        - ./config:/tmp/config
        #- ~/ksam_data/:/tmp/weka
